name: SonarQube Scan
on:
  push:
    branches:
      - main  # Run scan when pushing to main branch

jobs:
  sonar:
    runs-on: macos-latest  # Changed from ubuntu-latest to macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'  # Change if needed

      - name: Install SonarQube Scanner
        run: npm install -g sonarqube-scanner

      - name: SonarQube Scan
        env:
          SONAR_HOST_URL: "https://7cd8-2405-201-c039-802a-5044-f101-71e3-97ee.ngrok-free.app"  # Change if using a remote SonarQube server
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=WeatherApp \
            -Dsonar.sources=src \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
